---
# tasks/main.yml

- name: ocStore | Log | Enumerate log files
  find:
    paths: "{{ ocstore_www_root }}/{{ ocstore_shared_dir }}/{{ item.path }}"
    file_type: "any"
    patterns: "{{ item.patterns }}"
    use_regex: True
  with_flattened:
    - "{{ ocstore_log_path }}"
  register: ocstore_log_files
  when: ocstore_log_clean is defined and ocstore_log_clean == "yes"

- name: ocStore | Log | Delete log files
  file:
    path: "{{ item.1.path }}"
    state: absent
  with_subelements:
     - "{{ ocstore_log_files.results }}"
     - files
  when: ocstore_log_clean is defined and ocstore_log_clean == "yes"
